[workspace]
resolver = "2"
members = [
    "crates/*",
]

[workspace.package]
authors = ["Teoh Han Hui <teohhanhui@gmail.com>"]
edition = "2021"
rust-version = "1.65"
repository = "https://github.com/bowtieworks/automerge_orm"
license = "Apache-2.0"

[workspace.dependencies]
automerge = { git = "https://github.com/bowtieworks/automerge.git", branch = "automerge3" }
automerge-test = { git = "https://github.com/bowtieworks/automerge.git", branch = "automerge3" }
automerge_repo = { git = "https://github.com/bowtieworks/automerge-repo-rs.git", branch = "automerge3" }
autosurgeon = { git = "https://github.com/bowtieworks/autosurgeon.git", branch = "automerge3" }
